---
title: "Kable Learning"
author: "Ian McDonald"
date: "4/6/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```


```{r}
knitr::kable(head(mtcars[, 1:4]), "pipe")
```


```{r}
knitr::kable(mtcars[1:2, 1:2], "html")

```
```{r}
knitr::kable(head(mtcars[, 1:4]), "rst")

```

```{r}
iris2 <- head(iris)
# knitr::kable(iris2, col.names = names(iris))
# knitr::kable(iris2, col.names = gsub("[.]", " ", names(iris)))
# knitr::kable(
#   iris2,
#   col.names = c('We', 'Need', 'Five', 'Names', 'Here')
# )
# knitr::kable(iris2, align = "lccrr", caption = "Webster vs. Huntington-Hill")
# 
# kable(data.frame(a = 1:3, b = 4:6), caption = "CENTER") %>%
#   kable_styling(bootstrap_options = "striped", position = "center")

d <- cbind(X1 = runif(3), X2 = 10^c(3, 5, 7), X3 = rnorm(3, 
  0, 1000))

knitr::kable(d, digits = 3, format.args = list(big.mark = ",", 
  scientific = FALSE))

m <- lm(dist ~ speed, data = cars)
d <- coef(summary(m))
knitr::kable(d)
```

